import Link from "next/link";
import {projects} from "./projects";
export default function Home(){return <main>
<header><Link href="/" className="brand">BLUO<span>•</span></Link><nav><a href="#work">Work</a><a href="#approach">Approach</a><a href="https://bluo.co.uk/#contact">Start a project ↗</a></nav></header>
<section className="hero"><div className="eyebrow">SELECTED WORK / FREDDIE LEY</div><h1>Websites built to<br/><em>move people.</em></h1><p>Independent web design & development for businesses that want a sharper digital presence — without agency layers.</p><a className="button" href="https://bluo.co.uk/#contact">Start a project <span>↗</span></a><div className="hero-note"><span>03</span> CONCEPTS / COMPLETE EXPERIENCES / MOBILE-FIRST</div></section>
<section id="work" className="work"><div className="section-head"><span>01 — SELECTED WORK</span><p>Concept projects built to show how Bluo turns a real business brief into a complete digital experience.</p></div><div className="grid">{projects.map((p,i)=><Link href={"/work/"+p.slug} className={"project "+p.accent} key={p.slug}><div className="browser"><div className="browserbar"><i/><i/><i/><small>bluo / {p.slug}</small></div><div className="screen" style={{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.04) 25%,rgba(0,0,0,.78) 100%),url("${p.heroImage}")`}}><span className="screen-index">0{i+1}</span><div className="screen-copy"><strong>{p.title}</strong><b>{p.tagline}</b></div></div></div><div className="project-meta"><div><span>{p.category}</span><h2>{p.title}</h2><p>{p.description}</p></div><span className="arrow">↗</span></div></Link>)}</div></section>
<section id="approach" className="approach"><div className="section-head"><span>02 — APPROACH</span></div><div className="approach-grid"><h2>Small studio energy.<br/><em>Serious execution.</em></h2><div><p>Every project starts with the actual business problem: what needs to be clearer, easier or more convincing for the person visiting?</p><p>I design and build the answer directly — mobile-first, fast, and without unnecessary layers between you and the person making the site.</p><div className="approach-points"><span>01 / Clear structure</span><span>02 / Strong visual identity</span><span>03 / Built to convert</span></div></div></div></section>
<footer><span>BLUO / WEB DESIGN & DEVELOPMENT</span><span>Built by Freddie Ley · Southampton, UK</span></footer>
</main>}
