export type Project={
  slug:string; category:string; title:string; tagline:string; description:string; accent:string;
  pages:string[]; features:string[]; status:string; eyebrow:string; cta:string; stats:string[];
  heroImage:string; gallery:string[]; proof:string[]; testimonial:string;
};
export const projects:Project[]=[
{slug:"northline-barbers",category:"Concept / Barber",title:"Northline Barbers",tagline:"Sharp cuts. Simple booking.",description:"A fast, image-led barber website designed around the three things a customer needs: see the work, understand the services and book a chair.",accent:"lime",eyebrow:"CUTS / GROOMING / SOUTHAMPTON",cta:"Book a chair",pages:["Home","Services","Gallery","About","Contact"],features:["Visual cut gallery","Service + price grid","Sticky booking CTA","Location + opening hours"],status:"Concept project",stats:["12 styles","From £22","Open 7 days"],heroImage:"https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=1800&q=85",gallery:["https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1622296089863-eb7fc6b3c2a7?auto=format&fit=crop&w=1000&q=85"],proof:["Easy online booking","Clear service pricing","Mobile-first experience"],testimonial:"The whole point is speed: a customer should know what we do and how to book within seconds."},
{slug:"ember-table",category:"Concept / Restaurant",title:"Ember Table",tagline:"Good food. Easy decisions.",description:"A warm, editorial restaurant concept where photography, menu hierarchy and reservations do the selling. Built to make a hungry visitor want to book.",accent:"orange",eyebrow:"DINNER / WINE / WEEKEND",cta:"Reserve a table",pages:["Home","Menu","Story","Private Dining","Contact"],features:["Menu-first browsing","Dish-led photography","Reservation path","Events + private dining"],status:"Concept project",stats:["Seasonal menu","7 days","Book online"],heroImage:"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1800&q=85",gallery:["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1000&q=85"],proof:["Menu within one tap","Reservations always visible","Storytelling through photography"],testimonial:"The website should feel like the first course — enough to build appetite, never enough to get in the way."},
{slug:"forgeworks",category:"Concept / Trades",title:"Forgeworks",tagline:"Turn searches into enquiries.",description:"A practical trades concept designed for the moment someone needs help. Strong proof, clear services, project examples and a quote path remove hesitation.",accent:"blue",eyebrow:"BUILD / REPAIR / MAINTAIN",cta:"Request a quote",pages:["Home","Services","Projects","About","Contact"],features:["Trust + accreditation bar","Service comparison","Before / after projects","Quote-first conversion path"],status:"Concept project",stats:["20+ years","Free quotes","Local team"],heroImage:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1800&q=85",gallery:["https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1000&q=85"],proof:["Clear quote path","Visible proof of work","Trust signals above the fold"],testimonial:"People don't need a complicated site. They need confidence that we're the right team for the job."}
];
export const getProject=(slug:string)=>projects.find(p=>p.slug===slug);
